version: '3'
services:
  wordpress:
    build: ../
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* If you want to add any extra wordpress config */
        # define('WP_ALLOW_MULTISITE', true );
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USERNAME: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: